- name: install nginx
  hosts: localhost
  tasks:
    - name: nginx latest install
      ansible.builtin.yum:
        name: nginx
        state: installed

- name: start nginx
  hosts: localhost
  tasks:
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes


